// Mocks generated by Mockito 5.2.0 from annotations
// in foodie_kyoto_post_app/test/places_data_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:google_maps_webservice/src/core.dart' as _i5;
import 'package:google_maps_webservice/src/places.dart' as _i3;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUri_0 extends _i1.Fake implements Uri {}

class _FakeClient_1 extends _i1.Fake implements _i2.Client {}

class _FakePlacesSearchResponse_2 extends _i1.Fake
    implements _i3.PlacesSearchResponse {}

class _FakePlacesDetailsResponse_3 extends _i1.Fake
    implements _i3.PlacesDetailsResponse {}

class _FakePlacesAutocompleteResponse_4 extends _i1.Fake
    implements _i3.PlacesAutocompleteResponse {}

class _FakeResponse_5 extends _i1.Fake implements _i2.Response {}

/// A class which mocks [GoogleMapsPlaces].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleMapsPlaces extends _i1.Mock implements _i3.GoogleMapsPlaces {
  MockGoogleMapsPlaces() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Uri get url =>
      (super.noSuchMethod(Invocation.getter(#url), returnValue: _FakeUri_0())
          as Uri);
  @override
  _i2.Client get httpClient =>
      (super.noSuchMethod(Invocation.getter(#httpClient),
          returnValue: _FakeClient_1()) as _i2.Client);
  @override
  _i4.Future<_i3.PlacesSearchResponse> searchNearbyWithRadius(
          _i5.Location? location, num? radius,
          {String? type,
          String? keyword,
          String? language,
          _i3.PriceLevel? minprice,
          _i3.PriceLevel? maxprice,
          String? name,
          String? pagetoken}) =>
      (super.noSuchMethod(
              Invocation.method(#searchNearbyWithRadius, [
                location,
                radius
              ], {
                #type: type,
                #keyword: keyword,
                #language: language,
                #minprice: minprice,
                #maxprice: maxprice,
                #name: name,
                #pagetoken: pagetoken
              }),
              returnValue: Future<_i3.PlacesSearchResponse>.value(
                  _FakePlacesSearchResponse_2()))
          as _i4.Future<_i3.PlacesSearchResponse>);
  @override
  _i4.Future<_i3.PlacesSearchResponse> searchNearbyWithRankBy(
          _i5.Location? location, String? rankby,
          {String? type,
          String? keyword,
          String? language,
          _i3.PriceLevel? minprice,
          _i3.PriceLevel? maxprice,
          String? name,
          String? pagetoken}) =>
      (super.noSuchMethod(
              Invocation.method(#searchNearbyWithRankBy, [
                location,
                rankby
              ], {
                #type: type,
                #keyword: keyword,
                #language: language,
                #minprice: minprice,
                #maxprice: maxprice,
                #name: name,
                #pagetoken: pagetoken
              }),
              returnValue: Future<_i3.PlacesSearchResponse>.value(
                  _FakePlacesSearchResponse_2()))
          as _i4.Future<_i3.PlacesSearchResponse>);
  @override
  _i4.Future<_i3.PlacesSearchResponse> searchByText(String? query,
          {_i5.Location? location,
          num? radius,
          _i3.PriceLevel? minprice,
          _i3.PriceLevel? maxprice,
          bool? opennow = false,
          String? type,
          String? pagetoken,
          String? language,
          String? region}) =>
      (super.noSuchMethod(
              Invocation.method(#searchByText, [
                query
              ], {
                #location: location,
                #radius: radius,
                #minprice: minprice,
                #maxprice: maxprice,
                #opennow: opennow,
                #type: type,
                #pagetoken: pagetoken,
                #language: language,
                #region: region
              }),
              returnValue: Future<_i3.PlacesSearchResponse>.value(
                  _FakePlacesSearchResponse_2()))
          as _i4.Future<_i3.PlacesSearchResponse>);
  @override
  _i4.Future<_i3.PlacesDetailsResponse> getDetailsByPlaceId(String? placeId,
          {String? sessionToken,
          List<String>? fields = const [],
          String? language,
          String? region}) =>
      (super.noSuchMethod(
              Invocation.method(#getDetailsByPlaceId, [
                placeId
              ], {
                #sessionToken: sessionToken,
                #fields: fields,
                #language: language,
                #region: region
              }),
              returnValue: Future<_i3.PlacesDetailsResponse>.value(
                  _FakePlacesDetailsResponse_3()))
          as _i4.Future<_i3.PlacesDetailsResponse>);
  @override
  _i4.Future<_i3.PlacesDetailsResponse> getDetailsByReference(String? reference,
          {String? sessionToken,
          List<String>? fields = const [],
          String? language}) =>
      (super.noSuchMethod(
              Invocation.method(#getDetailsByReference, [
                reference
              ], {
                #sessionToken: sessionToken,
                #fields: fields,
                #language: language
              }),
              returnValue: Future<_i3.PlacesDetailsResponse>.value(
                  _FakePlacesDetailsResponse_3()))
          as _i4.Future<_i3.PlacesDetailsResponse>);
  @override
  _i4.Future<_i3.PlacesAutocompleteResponse> autocomplete(String? input,
          {String? sessionToken,
          num? offset,
          _i5.Location? origin,
          _i5.Location? location,
          num? radius,
          String? language,
          List<String>? types = const [],
          List<_i5.Component>? components = const [],
          bool? strictbounds = false,
          String? region}) =>
      (super.noSuchMethod(
              Invocation.method(#autocomplete, [
                input
              ], {
                #sessionToken: sessionToken,
                #offset: offset,
                #origin: origin,
                #location: location,
                #radius: radius,
                #language: language,
                #types: types,
                #components: components,
                #strictbounds: strictbounds,
                #region: region
              }),
              returnValue: Future<_i3.PlacesAutocompleteResponse>.value(
                  _FakePlacesAutocompleteResponse_4()))
          as _i4.Future<_i3.PlacesAutocompleteResponse>);
  @override
  _i4.Future<_i3.PlacesAutocompleteResponse> queryAutocomplete(String? input,
          {num? offset,
          _i5.Location? location,
          num? radius,
          String? language}) =>
      (super.noSuchMethod(
              Invocation.method(#queryAutocomplete, [
                input
              ], {
                #offset: offset,
                #location: location,
                #radius: radius,
                #language: language
              }),
              returnValue: Future<_i3.PlacesAutocompleteResponse>.value(
                  _FakePlacesAutocompleteResponse_4()))
          as _i4.Future<_i3.PlacesAutocompleteResponse>);
  @override
  String buildNearbySearchUrl(
          {_i5.Location? location,
          num? radius,
          String? type,
          String? keyword,
          String? language,
          _i3.PriceLevel? minprice,
          _i3.PriceLevel? maxprice,
          String? name,
          String? rankby,
          String? pagetoken}) =>
      (super.noSuchMethod(
          Invocation.method(#buildNearbySearchUrl, [], {
            #location: location,
            #radius: radius,
            #type: type,
            #keyword: keyword,
            #language: language,
            #minprice: minprice,
            #maxprice: maxprice,
            #name: name,
            #rankby: rankby,
            #pagetoken: pagetoken
          }),
          returnValue: '') as String);
  @override
  String buildTextSearchUrl(
          {String? query,
          _i5.Location? location,
          num? radius,
          _i3.PriceLevel? minprice,
          _i3.PriceLevel? maxprice,
          bool? opennow = false,
          String? type,
          String? pagetoken,
          String? language,
          String? region}) =>
      (super.noSuchMethod(
          Invocation.method(#buildTextSearchUrl, [], {
            #query: query,
            #location: location,
            #radius: radius,
            #minprice: minprice,
            #maxprice: maxprice,
            #opennow: opennow,
            #type: type,
            #pagetoken: pagetoken,
            #language: language,
            #region: region
          }),
          returnValue: '') as String);
  @override
  String buildDetailsUrl(
          {String? placeId,
          String? reference,
          String? sessionToken,
          String? language,
          List<String>? fields = const [],
          String? region}) =>
      (super.noSuchMethod(
          Invocation.method(#buildDetailsUrl, [], {
            #placeId: placeId,
            #reference: reference,
            #sessionToken: sessionToken,
            #language: language,
            #fields: fields,
            #region: region
          }),
          returnValue: '') as String);
  @override
  String buildAutocompleteUrl(
          {String? input,
          String? sessionToken,
          num? offset,
          _i5.Location? origin,
          _i5.Location? location,
          num? radius,
          String? language,
          List<String>? types = const [],
          List<_i5.Component>? components = const [],
          bool? strictbounds = false,
          String? region}) =>
      (super.noSuchMethod(
          Invocation.method(#buildAutocompleteUrl, [], {
            #input: input,
            #sessionToken: sessionToken,
            #offset: offset,
            #origin: origin,
            #location: location,
            #radius: radius,
            #language: language,
            #types: types,
            #components: components,
            #strictbounds: strictbounds,
            #region: region
          }),
          returnValue: '') as String);
  @override
  String buildQueryAutocompleteUrl(
          {String? input,
          num? offset,
          _i5.Location? location,
          num? radius,
          String? language}) =>
      (super.noSuchMethod(
          Invocation.method(#buildQueryAutocompleteUrl, [], {
            #input: input,
            #offset: offset,
            #location: location,
            #radius: radius,
            #language: language
          }),
          returnValue: '') as String);
  @override
  String buildPhotoUrl(
          {String? photoReference, int? maxWidth, int? maxHeight}) =>
      (super.noSuchMethod(
          Invocation.method(#buildPhotoUrl, [], {
            #photoReference: photoReference,
            #maxWidth: maxWidth,
            #maxHeight: maxHeight
          }),
          returnValue: '') as String);
  @override
  String buildQuery(Map<String, dynamic>? params) =>
      (super.noSuchMethod(Invocation.method(#buildQuery, [params]),
          returnValue: '') as String);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  _i4.Future<_i2.Response> doGet(String? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#doGet, [url], {#headers: headers}),
              returnValue: Future<_i2.Response>.value(_FakeResponse_5()))
          as _i4.Future<_i2.Response>);
  @override
  _i4.Future<_i2.Response> doPost(String? url, String? body,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#doPost, [url, body], {#headers: headers}),
              returnValue: Future<_i2.Response>.value(_FakeResponse_5()))
          as _i4.Future<_i2.Response>);
}
