// Mocks generated by Mockito 5.2.0 from annotations
// in foodie_kyoto_post_app/test/post_shop_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;
import 'dart:io' as _i11;

import 'package:foodie_kyoto_post_app/data/model/result.dart' as _i2;
import 'package:foodie_kyoto_post_app/domain/entity/foodie_prediction.dart'
    as _i7;
import 'package:foodie_kyoto_post_app/domain/entity/shop.dart' as _i5;
import 'package:foodie_kyoto_post_app/domain/entity/shop_detail.dart' as _i8;
import 'package:foodie_kyoto_post_app/domain/use_case/image_file_use_case.dart'
    as _i10;
import 'package:foodie_kyoto_post_app/domain/use_case/places_use_case.dart'
    as _i6;
import 'package:foodie_kyoto_post_app/domain/use_case/shop_image_use_case.dart'
    as _i9;
import 'package:foodie_kyoto_post_app/domain/use_case/shop_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeResult_0<T> extends _i1.Fake implements _i2.Result<T> {}

/// A class which mocks [ShopUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockShopUseCase extends _i1.Mock implements _i3.ShopUseCase {
  MockShopUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i5.Shop>>> fetchShops(
          {int? limit, String? cursor}) =>
      (super.noSuchMethod(
          Invocation.method(#fetchShops, [], {#limit: limit, #cursor: cursor}),
          returnValue: Future<_i2.Result<List<_i5.Shop>>>.value(
              _FakeResult_0<List<_i5.Shop>>())) as _i4
          .Future<_i2.Result<List<_i5.Shop>>>);
  @override
  _i4.Future<_i2.Result<void>> postShop({_i5.Shop? shop}) =>
      (super.noSuchMethod(Invocation.method(#postShop, [], {#shop: shop}),
              returnValue:
                  Future<_i2.Result<void>>.value(_FakeResult_0<void>()))
          as _i4.Future<_i2.Result<void>>);
  @override
  _i4.Future<_i2.Result<_i5.Shop?>> fetchShopByShopId({String? shopId}) =>
      (super.noSuchMethod(
              Invocation.method(#fetchShopByShopId, [], {#shopId: shopId}),
              returnValue: Future<_i2.Result<_i5.Shop?>>.value(
                  _FakeResult_0<_i5.Shop?>()))
          as _i4.Future<_i2.Result<_i5.Shop?>>);
}

/// A class which mocks [PlacesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlacesUseCase extends _i1.Mock implements _i6.PlacesUseCase {
  MockPlacesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void initGooglePlaces({String? apiKey}) => super.noSuchMethod(
      Invocation.method(#initGooglePlaces, [], {#apiKey: apiKey}),
      returnValueForMissingStub: null);
  @override
  _i4.Future<_i2.Result<List<_i7.FoodiePrediction>>> searchShopsByAutoComplete(
          {String? body}) =>
      (super.noSuchMethod(
              Invocation.method(#searchShopsByAutoComplete, [], {#body: body}),
              returnValue: Future<_i2.Result<List<_i7.FoodiePrediction>>>.value(
                  _FakeResult_0<List<_i7.FoodiePrediction>>()))
          as _i4.Future<_i2.Result<List<_i7.FoodiePrediction>>>);
  @override
  _i4.Future<_i2.Result<_i8.ShopDetail?>> searchShopDetailsByPlaceId(
          {String? placeId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #searchShopDetailsByPlaceId, [], {#placeId: placeId}),
              returnValue: Future<_i2.Result<_i8.ShopDetail?>>.value(
                  _FakeResult_0<_i8.ShopDetail?>()))
          as _i4.Future<_i2.Result<_i8.ShopDetail?>>);
}

/// A class which mocks [ShopImageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockShopImageUseCase extends _i1.Mock implements _i9.ShopImageUseCase {
  MockShopImageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<String?>> postImages(
          {String? path, String? shopId, String? fileName}) =>
      (super.noSuchMethod(
              Invocation.method(#postImages, [],
                  {#path: path, #shopId: shopId, #fileName: fileName}),
              returnValue:
                  Future<_i2.Result<String?>>.value(_FakeResult_0<String?>()))
          as _i4.Future<_i2.Result<String?>>);
  @override
  _i4.Future<_i2.Result<String?>> getImagesUrl(
          {String? path, String? shopId, String? fileName}) =>
      (super.noSuchMethod(
              Invocation.method(#getImagesUrl, [],
                  {#path: path, #shopId: shopId, #fileName: fileName}),
              returnValue:
                  Future<_i2.Result<String?>>.value(_FakeResult_0<String?>()))
          as _i4.Future<_i2.Result<String?>>);
  @override
  _i4.Future<_i2.Result<String>> deleteImages({String? shopId}) => (super
          .noSuchMethod(Invocation.method(#deleteImages, [], {#shopId: shopId}),
              returnValue:
                  Future<_i2.Result<String>>.value(_FakeResult_0<String>()))
      as _i4.Future<_i2.Result<String>>);
}

/// A class which mocks [ImageFileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageFileUseCase extends _i1.Mock implements _i10.ImageFileUseCase {
  MockImageFileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i11.File>>> pickMultiImage() =>
      (super.noSuchMethod(Invocation.method(#pickMultiImage, []),
              returnValue: Future<_i2.Result<List<_i11.File>>>.value(
                  _FakeResult_0<List<_i11.File>>()))
          as _i4.Future<_i2.Result<List<_i11.File>>>);
  @override
  _i4.Future<_i2.Result<_i11.File?>> pickImage() => (super.noSuchMethod(
          Invocation.method(#pickImage, []),
          returnValue:
              Future<_i2.Result<_i11.File?>>.value(_FakeResult_0<_i11.File?>()))
      as _i4.Future<_i2.Result<_i11.File?>>);
}
